version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    ports:
      - "44432:5432"
    environment:
      POSTGRES_USER: george
      POSTGRES_PASSWORD: washington
      POSTGRES_DB: relia_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local
